// Store current index for each category
const currentIndexes = {
    teasing: 0,
    blowjob: 0,
    pussylick: 0,
    pussy: 0,
    squirt: 0,
    asshole: 0,
    ass: 0,
    cum: 0,
    dominant: 0,
    cuckold: 0,
    balls: 0,
    massive: 0,
    bundle: 0,
    support: 0,
    ivyvip: 0,
    ambervip: 0,
    vrajeli: 0,
    dickrate: 0
};

// Track if the "End of Messages" has been reached for each category
const reachedEnd = {
    teasing: false,
    blowjob: false,
    pussylick: false,
    pussy: false,
    squirt: false,
    asshole: false,
    ass: false,
    cum: false,
    dominant: false,
    cuckold: false,
    balls: false,
    massive: false,
    bundle: false,
    support: false,
    ivyvip: false,
	ambervip: false,
	vrajeli: false,
	dickrate: false
};

// Messages for each category
const messages = {
    teasing: [
	
        "I want you baby to fuck so hard that we are going to make the best memorie of all time and beeing by your side would be more than a miracle 👉👌💦😏",
		"We can take care of each other so good and so well that no one did before, a new experience and a totally new world between us🥰 Satisfying each other with every single moment and second that we have to, use them as our pleasure and don't waste any😍 Fucking, anal, sucking, caressing and all that🤗",
		"I want to run my hands down between your legs, feeling your hard dick throbbing with desire as I suck every drop of cum out of you. The thought of your mouth working its magic, your tongue swirling around me, has me on edge 🥵🥵🥵",
        "I want you to unzip your pants and take out your cock for me and start jerking off slowly 😈",
		"If you're going to treat me right and keep me in the bedroom all the time, fucking and fucking all the time, even when you're sleeping I will suck your cock sometimes😈 that's the way I will wake you up, with the coffee, breakfast and a blowjob😏 I will take it in my mouth while is still sleeping and make you cum in my coffee because we don't have any milk left💦💦",
        "Fuckkkkk unzip your pants and start jerking slowly for me baby 😈🥵🥵🥵🥵💦💦💦",
		"I wish you were here with me rn so I could grind on top of you while you spank my fat ass and shove 2 fingers up my tight wet pussy, making my pussy so fucking wet 🥵💦",
		"All I hear is me screaming and water splashing loudly from how hard I'm getting fucked🥵🥵🥵",
		"I'm high with you, you're like a druuuug for me🥵🥵🥵🥵🥵 I just can't stop!! I want you to flip me in every position and fuck me nonstop, I don't want to stop, ever🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵🥵 I just found my treasure, my whole world, you are my universe and my addiction🙈 I need more cock pics😈 daddy, will you spoil me with the view of more dick pics?🤤🤤",
		"Yes love, I want to fuck you hard in every room of our house, in the shower, on the kitchen table, absolutely everywhere! I'm crazy for your dick! I can't stop thinking about anything else all day long! You are doing magic to me! 😈😻😻",
		"Let me tell u my biggest fantasy. I want u to tie me to a pole while standing on my feet, put a fuck machine under me with 2 dildos attached to double penetrate me. U control the fuck machine speeds while slapping me, spitting on me and talking dirty to me😈",
		"Yes, daddy! I will cum along with you! I will rock your world, I will ride you and grind on your hard dick all night long! I will make you forget about all your problems, I will make your brain fill your body will pleasure 🥵🥵🥵🥵",
		"I would love to enjoy the slow speed with you for longer, to hold my anger and my hunger for it, to make romantic love and bite heaven for a second and then we can get wild and have fun😈😈",
		"I will have it in my hand and the tip in my mouth and I will stop for a second, looking into your eyes, I will do puppy eyes and make you to want me more👀😊",
	    "I can do this only with you because we are both fucking crazy and untamed by no one, ppl these days don't know how to have fun🥵🥵🥵 But I don't care where we are, balcony, mall, park, street, Eiffel Tower, Chinese wall, McDonald's I won't give a fuck, I will undress and just fuck you, daddy!!!!😍👉👈🙏🙏🙏 That's all I dream and I will dream for weeks, months it's your about to explode cock, hard af and shaking desiring all my holes like I desire it deep inside my endless caves😍😍😍",
		"Oh yes, baby, unzip your pants and start stroking that hard cock for me. I want to watch you jerk off slowly, teasing me with every movement. Let me see the pleasure on your face, the way you crave me. Make me wetter with every stroke 👉👌💦",
		"I want you to unzip your pants and take out your cock for me and start jerking off slowly 😈 until your precum is visbile 😈 Then you have to make it sure you lube my ashhole with your precum 🥵 And put slowly into my ass, make sure to don't break up my asshole with your GIGA PENIS 🥵🥵🥵🥵🥵 Please, take care of my tiny little hole, ok babe? 🥵🥵🥵",
		"I would throw you on the bed and slowly take off your boxers. Then I would stare at your hard cock. I would slowly move my finger up the side of your dick. After that I would very slowly lick the side of your penis. I would swirl my tongue around the head of your dick. Then I’d suck on just the tip of your throbbing hard cock. I would then tickle and lick your balls😏😈",
		"Throw me on the floor, baby put me in doggy face down ass up🍑, pin me down by puttin ur foot on my head and start giving me the hardest backshots ever deep in my pussy🍆🍑😫🥵💦💦",
		"I wish you were here so fucking bad!! I'd want you to start by kissing my lips, then work your way down to my neck while playing with my hard nipples. Hearing me moan would make your cock rock hard as you suck on my tits and finger my tight little pussy... Eventually you'd word your tongue down to my asshole and eat me out as long as you want, making me beg you to fuck me!!!! 🥵🥵🥵 Finger-fucking my tight little asshole and then pulling out your fingers and make me taste myself while you rub my pussy at the same time 🤤🤤",
		"Then I want you to push me on my back and get on top of me and put your cock between my boobs and fuck them hard, I will be with my tongue out trying to reach the tip of your cock but you grab my neck and tell me to not be a bad girl and to listen to daddy🥵🥵🥵",
		"How about I wrap my huge boobs around your cock and massage it? I'll keep spitting on it too so it's well lubed up and I'll keep going until you're rock hard, throbbing and pulsating so fucking hard your cock's gonna feel like a vibrator in my tight little pussy 🥵🥵🥵 Put it between my boobs now and start fucking them, daddy PLEASE PLEASE PLEASE!!! I want you to fuck my boobs until your cock's ready to break my throat and tight little holes 💦💦💦💦💦",
		"After you push it in deep and you can see me coughing and trying to breathe, take it out and rub your spit, precum-covered cock all over my slutty face!! Slap me with it and ask me who's a good girl. I'll look you in the eyes deep, my makeup ruined and scream I am daddy, I'm your cumhungry good girl 😍😍😍 Then as a reward you spit in my mouth and shove it back in my throat balls deep again and hold it there for a few seconds, stopping me from breathing. Then once you see me struggle start fucking my face so hard and fast it starts to hurt",
		"I like it so much daddy I'm telling you this while breathing heavily and sighing 🥵, I spit in my palm and start massaging your balls and shoving them into my mouth along with your hot throbbing cock, I feel it pulsating in my mouth. I'm screaming desperately 'YES DADDY,FUCK MY ASS', I'm groaning and clenching my teeth out of pleasure when I say this, I want your cock in me, I want you to pound those soaked balls on my pussy while banging my ass please daddy give that hard throbbing cock to your worthless little whore 🥵",
		"You're throwing me on the ground, I'm on my fours and you tell me 'Don't you dare to move whore, I've got something bigger for that tiny hole' I'm sighing and breathing heavily 'Y..yes daddy, as you say' and procceed to lay my face on the floor and reach my cheeks and spread them for you 👉👈 🥵",
		"I want you to take complete control, pinning me down as you drive into me relentlessly, each thrust making me gasp for breath. Feel my body clenching around you, begging for more as you grab my hair, pulling me back into you while you spank my ass so hard it leaves me aching for days. The mix of pain and pleasure has me dripping, craving every inch of you as you push me further, making me yours completely 🥵💦🥵💦",
		"I can't wait to feel you getting harder in my mouth as I take you deeper, teasing you with every slow, wet stroke until you can't take it anymore 😏😏",
		"All night you'll keep fucking it and I will be screaming and you'll be cumming and cumming. 😈😈😈 You'll pound you so hard my face will be pinned to floor everything starts shaking around us how hard your fucking me 🥵🥵",
		"I also would like to take your cock between my boobs while he's resting, daddy, and spit on it and you just lay down and let me play with my toy please🥺 Will you let me do that? I would really be gentle and take care of it, I feel how hard is your cock and how bad wants me and that veins, omg, I can feel ever single one🥰",
		"You should tell me what I have to do, do you want me to lay on the floor head down and you to put your foot on my head and keep pouding my holes from behind one by one alternative and fucking rough like no one else, the end of the world is nearby so you have to fuck me for the next 10 lives too😈😈😈",
		"Please don't have your throbbing cock too much out of me because I'll be craving it and my mouth will be dripping because I need it and want it so bad🥵 My breath will be heavy and I will feel so much warm and heat, like thirsty or under so much heat, tongue out and mouth wide open, my face is red and want more🥵🥵🥵 Please give it to me, you teased me way too much already and I think I deserve it, I want you to lift me up and put me on the table or the chair and let's have our moment there too💋💕"
		
    ],
    blowjob: [
	
	    "I wanna hear you moan and put my hair behind my ears 💋 I would love that, me sucking it and you doing that and from time to time to push my head down to take it deeper🤤",
		"Imagine it's my devilish lips wrapped around it, taking it all deep into my throat while looking u in the eyes😈 But I won't be gentle, I'll gag on ch0ke on ur cock until spit drips out of my mouth and my face is painted with cum and saliva🤤🤤🤤",
		"I will give you a very sloppy blowjob and let the saliva slide over your balls and then go down with my tongue and start licking them off, sucking gently to not hurt you, maybe a bit😈😈 and keep jerking your cock until you're about to cum and I just get back up and take it deep in my throat and look into your eyes while I keep jerking you with one hand and with the other I massage your soft and big balls🥵🥵",
        "I would crawl to you on my fours, pull your pants down and start licking your cock from bottom to top when it's not fully hard yet, then move my tongue around the tip slurping all that precum, after that I would put it in my mouth cause I love it so much to feel it grow in my mouth.. 🥵🥵🙈",
		"I can't wait to get on my knees and show you what a filthy cumslut I can be, daddy . Your cock will be my favorite treat, and I'll devour it like a hungry whore, sucking and slurping every last drop of your delicious cum🤤🤤🤤",
		"I would just get on my knees in front of you, unzip your pants and take it out, licking the sides and then getting to your balls and suck and lick them gently🥰 Then getting my way up to the tip, licking and kissing it😍 I will put it slowly inside my mouth and with one hand I'll jerk you and with other hand I'll massage your balls😈",
        "Then I want you to place both of your arms on my head, grab my hair as well and make me hold my tongue out while shoving your cock inside my throat so it burns me and my tongue is reaching for those balls to make them soaking wet daddy 🥵🥵💦",
		"What about you get on top of me and start fucking my throat in that position?😈 While you touch my pussy and fingerfuck it, with 3 fingers😈 Getting me to gag and moan as hard as I can so you can feel the vibration of my throat on your tip😍",
		"I'd like to sit on the side of the bed with my head over the edge upside down and I want you to shove your cock deep inside my mouth , deep inside my throat and shove it really deep until you see a bulge in it and keep your cock right there and start to play with it inside of me 🥵🥵🥵🥵",
        "Then I'd push you on the edge of the bed, I look you in the eyes with a desperate look on my face and take that sloppy cock out of my mouth and start rubbing it against my cheeks, slap it on my forehead with a dumb smirk on my face, then put it back inside my mouth and start slurping the tip till I'm making dimples in my cheeks 💦🍆👅",
		"The thought of feeling you throbbing against my tongue has me so turned on... I want to make you lose control as I suck you slow and deep, taking you all the way down until you can't hold back anymore 🥵🥵🥵🥵",
		"I would suck it like that, looking into your eyes😏 with puppy eyes and begging for your cum to fill my throat first, I will start sucking you harder and faster while we go, until I get it and get your cock clean, wet, rock hard and just ready for my tight little holes😈😈",
		"After you push it in deep and you can see me coughing and trying to breathe, take it out and rub your spit, precum-covered cock all over my slutty face!! Slap me with it and ask me who's a good girl. I'll look you in the eyes deep, my makeup ruined and scream I am daddy, I'm your cumhungry good girl 😍😍😍 Then as a reward you spit in my mouth and shove it back in my throat balls deep again and hold it there for a few seconds, stopping me from breathing. Then once you see me struggle start fucking my face so hard and fast it starts to hurt",
		"I want u to put me in a 69, me on top, tongue fuck my holes and slurp on my pussy juices while u fuck my face going deeper, faster, harder with each thrust. Fuck my throat like a pussy, daddy"
    ],
    pussylick: [
	
        "Oh yes fuckkkk! Lick me from behind my love 😈😈😈😈 You make my body trembling fuckkkk 🥵🥵🥵 What are you doing to me.... You tongue feels so fucking good.... Eat my pussy, lick it harder, drink all my pusys juices 🥵🥵🥵🥵🥵🥵",
		"Omg ,yes , I want that to wrap my legs around your head and to squeeze then you touch in my favorite place and once you start to play with your fingers inside my pussy is going to feel even better so we better do a 69 so I can taste you cock too 🥵🥵🥵",
        "I want you to put me in a 69, me on the bottom and slurp on my pussy juices🤤💦💦 and finger fuck my little holes to make them wet sloppy and ready for your hard cock🍆🥵 All while you're thrusting your cock deep in my mouth🍆, fucking my throat like a pussy🥵😏😈",
        "I will bury your face😜 in my pussy in 69 so you can play with my asshole,😈 but don't forget that you have my panties👙 in your mouth👄, I'll give you air from time to time, depends how hard and loud will you scream🥵😱🔥🤤",
		"Omg... give me the biggest orgasm of my life and lick all the delicious juices out of my pussy, then stick your tongue up my ass so I can feel you tickle me! FUCK... why are you doing this to me? You want me to cum instantly? 🥵🥵",
		"After you slurp all my pussy juices and after I take your cock deep inside my throat, massaging with my tongue and my soft lips 👅👅👅 Throw me in doggy and stick your wet cock in my tight little pussy, I want it to fucking bad right now 🥵🥵🥵🥵💦💦💦💦 Look what are you doing to me... I'm horny as fuck... I wish you were here with me fucking me so good.... You're so good, I'm your cum dumpster 🥵🥵🥵💦💦💦💦 Give me all your sweet juicy cum 🥵🥵🥵🥵",
		"I want you to put me in a 69, me on the bottom and slurp on my pussy juices🤤💦💦 and finger fuck my little holes to make them wet sloppy and ready for your hard cock🍆🥵 All while you're thrusting your cock deep in my mouth🍆, fucking my throat like a pussy🥵😏😈",
		"My pussy is all yours, I cover your face and your mouth with my cum and squirt, I will do a mess and get the sheets wet, all because of your great skills, love🥵🥵 I just want it 24/7, until I have nothing left, come up and kiss me and suck my nipples then get back there and keep doing what you were doing, you're the best💋🤤"
    ],
    pussy: [
	    
		"My pussy is so ready to taste your cock baby 🥵 spread my legs apart and burry that cock in my sweet pussy 🥵💦",
		"Slowly in and out, but all out, that's how I love it, have the rhythm together will make us cum together at the same time, that's a very hard thing to do but if we are a match we can do it for sure. Romantic, rough, depends on the ppl and the way you do it. Keep me up there and I'll try to pull you closer to me with my legs and put it inside😍",
	    "My toy is not enough, love! I need you right now! I need you to thrust your throbing cock in my pussy 🥵🥵 Make me reach orgasm, fuck me as HARD as you can, please, daddy 🥵😍",
		"I'm a nympho so you'll have to😈 Giving me no breaks like I will do to you😏So slide it back in and don't take it out, not even a second😈😈 Because I will take it in my hand and put it right back in, I don't want to hear you saying that you can't anymore, you're stuck with me and my sweet pussy and for sure my boobs if that's what you want😈😈 I just want your cum, all of it😏",
		"I want to be tied up and blindfolded and you to eat me up and kiss me and turn me around however you want to and then to fuck me so hard and rough until I scream that hard so you'll have to put my panties in my mouth to make me shut up and then if that's not working you'll have to put your cock deep in my throat😈😈",
        "Yes, daddy, I want that, I want your cock to be deep inside me and make me scream my lungs out and have no mercy and and and everything🥵🥵 just touch every inch of me and do whatever you want, I'm your fuckdoll from now on😈",
        "Just let the tip of your cock tease my wet pussy, making me drip with anticipation 😍. I’ll try to push you in, but you’ll hold back, making me giggle and beg for more. Then, just when I’m least expecting it, you’ll thrust in hard, making me moan in surprise 😈. Lift me onto the kitchen counter, kissing my neck and breasts as you slowly slide in and out of me, driving me wild with every movement 🥵",
        "Have no mercy, you can bend me over and start fucking my pussy rough🥵 but don't forget about my asshole, he needs some filling too😈 You can cum in my pussy and my ass alternative and then you can watch the cum sliding down my pussy from my asshole!! I will take it with my fingers and eat it all😈😈",
		"🥵🥵 I'd love to know how you taste when you cum a bit for me when you touch the tip of my throat with your hard cock and glans! I want to feel how I blow your cock and you grab me from my hair, look at my eyes and ask me to jump over your cock! 😈😈😈",
		"Hmmmmm baby I'm so fucking wet rn you've made me took my toy and fuck myself imagining you fuck me 🥵🥵🥵 I'm so horny and wet, I want to feel your dick 🥵 I want you to fuck me in all positions and hold your hand to my mouth so I can't scream 🥵 And I want to shout your name while you shove it up my ass and pull my hair 😈 I want to feel your dick up to my stomach 💦💦 Fuck me and I have to scream as loud as I can for all the neighbors to hear 🥵🥵 And I want to suck your dick and fuck me in my mouth like you fuck me in my pussy, baby 🥵🥵",
		"I want you to fuck me so hard that I can't help but scream with every thrust. Take me from behind, gripping my hips as you drive your cock deep into my tight pussy. Make me moan and yell, my screams echoing through the room as you push me to the brink of ecstasy. I want to feel every inch of you pounding into me, my body trembling with the force, of your pleasure. Don't hold back make me lose control and scream louder than ever before 😈🔥",
		"I am so fucking wet, ready for your cock, my pussy is juicy as fuck, come and lick all my fluids then stick your juicy cock deep inside 💦🥵🥵🥵 Your cock is my bible 🥵🥵🥵🥵 You're driving me crazy, fucking me so fucking good... What are you doing to me my love? 😏👅💦💦💦 I am horny as fuck and I need your cock, I need it right now 🙈🥵🥵😍💦💦💦💦",
		"I want to ride you so bad, gently at first so we can mix your precum and the cum left on it and my pussy juices😍😍 then jumping mercyless on your rock hard cock until you cum deep inside, I will scream my lungs out and tell you how good is your cock feeling inside me🥵🥵",
		"Buckle up, buckaroo hahaha because I'm gonna ride you like a maniac!! I'm gonna ride your cock so fucking hard and I'll squeeze it so hard with my tight bootyhole that you're gonna cum so hard it's gonna lower your sperm count hahaha 😈😈 I think it's time for you to see what a good cock worshipper and cumslut I can be for you, daddy 🥵🥵🥵",
		"Don't slide it in yet, tip tease me my wet pussy and make me dripping 😍 I will try to get it in and we'll have a little laugh at first because I can't hold myself and I'll ask you to do it and you just slide it fast and unexpected inside, surprising me 😍😍Lift me up on the counter and keep kissing my lips, going down to my boobs and slowly go in and out in my pussy with your cock🥵🥵",
		"I want you to fuck me in all positions, all night long, to scream until my throat hurts on the second day, I want you to fuck me with your big dick the way you like, to destroy my pussy and pull my hair and stick a finger in my ass while you fuck me in my pussy, that's what I want, I want to feel your dick in all my holes and fuck me as if you were fucking me for the last time, as if it were the last day on earth 🥵🥵🥵🥵💦💦💦💦💦😈😈",
		"I wish you were here so fucking bad!! I'd want you to start by kissing my lips, then work your way down to my neck while playing with my hard nipples Hearing me moan would make your cock rock hard as you suck on my tits and finger my tight little pussy Eventually you'd word your tongue down to my clit and eat me out as long as you want, making me beg you to fuck me Then finally you'd slip the tip of your cock in my pussy as my moans get louder As you go deeper, harder and faster I become louder and louder till my moans turn into screams, 🥵 You'd throw my legs on my shoulders and fuck me long, deep and hard, pounding my pussy all night long and make me squirt so much I'd flood the bedMake me scream so much I'd lose my voice Make me shake so much I'd be so sore the next day I wouldn't be able to walk🥵🥵🥵🥵🥵🥵",
		"OH YES DADDY, I WANT YOU TO POUND MY PUSSY AND SQUEEZE MY BOOBS RIGHT NOW, DRILLING AND DRILLING WITH THAT FUCKING COCK OF YOURS!!! DADDY???? PLEASEEEEEE I want all of you inside me, inside my throat, pussy, asshole, armpits, feet, eyes, between my legs, neck, I don't care!!! just fucking all of me and touch every fucking inch of my body with that PERFECT cock of yours🥵🥵🥵🥵🥵🥵🥵 I just can't hole myself when I'm playing with you, my mind and body just goes crazy, you drive me crazy and I can't, just can't!!! I won't hold myself and have no hold backs, just fucking and touching and do what the fuck I want and what the fuck you want, do you want me to be your pet?? I will, do you want me to sleep and cook, do the laundry, cleaning, shopping with your cock in my mouth or holes?? I WILL DO IT!!! So just fuck me as hard as you can and spoil me, daddy, spoil me in every way and how you want!!! I have no words and nothing, I'm just a doll like I always say, no thoughts nothing!!! All yours for your pleasure and your desires, we can be whatever the fuck we want together🥵🥵🥵🥵🥵😈😈"
    ],
    squirt: [
	
        "I want you to make me lay in my own squirt and fuck me more while I'm slurping my own juice off the floor 🥵",
		"Imagine me squirting all over the bed as you fuck me with your hard cock 😈💦. I’ll be so drenched that the sheets will be soaked with my wetness. Each thrust will push me closer to the edge, and I’ll be crying out in ecstasy, feeling my juices gush out with every powerful movement. My body will writhe beneath you, craving more of your touch as I release wave after wave of intense pleasure 💋🔥",
        "I want your cock so bad, I'm horny af and I will squirt all over it and make it so wet and keep going until I'll drain your balls inside me and I want to get down there and lick and eat all the mixed juice🥵🥵",
        "Giving me strong thrusts after just staying for a bit inside, not moving at all, leaving all the precum in there🥵 I will start squirt all over your body in seconds, just rub my clit for a little bit and grab my boobs and kiss me as passionate you can😍😍",
		"Imagine me squirting all over your fingers as you explore my dripping pussy 😈💦. Your touch will drive me wild, and my juices will gush out with each stroke. I’ll be moaning and writhing, my body responding to your every movement as you bring me to the brink of ecstasy. My squirting will be uncontrollable, and I’ll be left panting and satisfied from the intense pleasure you give me 💋🔥",
		"Doing all kind of naughty stuff, ahhhhhhhhhhhhhhhhhh just imagining how many things we'd do together, OMG, we get so much along and want the same things🤤🤤 Having no mercy for me that's the thing, tie me up and use me like your fuckdoll do whatever you want and need, dream, desire to me🥵🥵🥵🥵🥵Because I will start squirting and get you wet and shiny💦🤤🤤",
		"I will take care of your hard cock😈 Do you think I'm not good enough? I will get on top of you and start jumping like crazy on it, my boobs are bouncing around and my ass going up and down on it, I want you to go deep inside me and make me squirt all over your cock, belly and chest🥵🥵 I think it will get over your face and mouth too if you'll be a good boy and stay still😈",
		"I can’t wait to feel you make me squirt all over your cock as you fuck me hard 😈💦. My pussy will be so wet and eager, my juices spilling out with each thrust. I’ll be moaning your name, my body shaking with every powerful stroke. My wetness will cover you completely, and I’ll be lost in the intensity of my orgasms, feeling every inch of pleasure you give me. The sight of my juices flowing freely will drive us both wild 💋🔥",
		"Daddy, I will keep calling you daddy until I can't talk anymore because of your hard cock pounding my throat, that will be the only moment I won't calll you daddy😈😈 Or from screaming too hard 🥵 I want that, put me on the chair and keep pounding and pounding until I squirt all over the place and get us so wet and make a biiiiiiiiig mess, daddy, your fuckdoll need and wants moreeeeee🥵🥵🥵 I think you can handle me, you're a king, daddy🔥🔥🔥🔥",
		"Fuckkkk, daddyyy!! Everytime we'll be fucking we'll rise the ocean level from how much squirt and cum we'll produce, spit and sweat!! Earthquakes everywhere, the world shaking and the sky erupting and falling down!! Daddy you are my god and your cock is my bible, do you understand?!?!😍😍😍😍😍😈🥵",
		"I will push you deeper and deeper, begging you to go a bit faster because I'm close, I feel your wet and soft tongue on my clit and your fingers moving slowly inside me🤗 I'm about to squirt, love, pleaseee, go faster and you'll get all my juice for sure, you're doing great, right there don't stop and keep going the same speed and the same spot🥵 Put one more finger inside, I want 3 and shove them harder but not faster, feel all inside my pussy, I want to feel you everywhere, like you want to get inside me, all of you😈"
    ],
    asshole: [
	
        "Take me however you want, but make sure your tongue finds its way to my asshole. I want you to bury your face between my cheeks, licking me with a wild, rough intensity. Feel me squirm and gasp as you take control, making my body surrender to every deep lick and stroke of your tongue. I need to feel your hunger for me, your tongue exploring every forbidden place and making me lose my mind with pleasure 😏",
        "I need you to hold me down and make me feel your tongue exploring my tight asshole. Start with slow, deep licks that make my body arch with desire, then go faster, rougher, until I'm gasping for breath. I want to feel your tongue pushing inside, claiming every inch, teasing me mercilessly as I moan and beg for more. Make me feel every moment of it, knowing you’re in control and loving every second 😈",
        "The thought of your tongue exploring my asshole sends shivers down my spine. I want to feel every lick and flick, your warm breath making me tremble with anticipation. Your skilled tongue teasing and driving me wild will make me moan uncontrollably, pushing me to new heights of pleasure 😈💦",
		"Don’t hold back press your face against my ass and lick me hard, your tongue sliding over my asshole with rough, urgent movements. I want to feel your need, your hunger as you devour me, every lick sending shockwaves through my body. Make me cry out as you go deeper, teasing and tasting me with a relentless intensity, making me crave more until I can’t take it anymore and explode with pleasure 😈🔥",
		"I want to feel your strong hands gripping my ass as your tongue goes straight to my asshole, licking me with a raw, animalistic passion. Start with firm, forceful strokes, and then get rougher, pushing me to the edge with every deep lick. I need to feel the pressure of your mouth against me, the way your tongue moves inside, making me whimper with pleasure as you taste every inch of me 😏💦",
		"I’m fantasizing about your tongue on my asshole, each lick sending waves of pleasure through my body. I want you to explore every part of me, teasing and pleasing until I’m moaning with delight. Your warm, wet touch will make me shiver and crave more, pushing me to the edge of ecstasy 😈🔥",
		"I crave the sensation of your tongue on my asshole, slowly and thoroughly exploring every inch. Each lick will make me quiver, my body arching with delight as you take your time savoring the taste and feel. The way you make me lose control with your teasing touch is absolutely irresistible 😏🔥"
    ],
    ass: [
	
	    "Mmm. I want my ass wrapped around your cock. Feeling how wet I am. How it grabs you. Feeling every orgasm. Feeling my whole body spam with every orgasm I have. 🥵🥵🥵🥵🥵",
        "You're starting to rub your dick against my soaked ass, sticking the tip in then pulling out a few times, teasing me while I'm moaning and beggind you to fuck this little whore in the ass...please daddy 🥵🥵🙈",
        "You say 'Spread that ass harder whore' and then when I expect less you're shoving it forcefully in me all the way to the end of it and start pounding my ass, slapping your balls against my pussy. I'm moaning your name and groaning for that cock starting to yell 'YESS DADDY, GRAB ME AND USE ME LIKE YOUR TOY' 🥵🥵",
        "FUCK ME DADDY, MAKE THIS ASS YOURS, I WANT TO FEEL EVERY DROP OF THAT HOT POURING CUM OUT OF THIS ASS, I NEED TO FEEL YOUR FINGERS IN MY PUSSY AS WELL SO I CAN SQUIRT FOR YOU DADDY 🥵🥵🥵💦💦",
		"I want you to use me like your own toy 😈. Tie me to the bed and fuck my mouth, pussy, and asshole with no limits. I crave feeling your cock so deep inside me that it makes me unable to walk. Make me your bitch, putting those balls in my ass and cumming on my face daily, making me tell you how delicious it is 🥵",
		"Daddy , I want you to put me in a 69, me on the bottom with my head at the edge of the bed, and slurp on my pussy juices and finger fuck my little holes to make them wet sloppy and ready for your hard cock. All while you're thrusting ur cock deep in my mouth, fucking my throat like a pussy😍 When you get bored of my throat stand up and grab me by the hair, put me in missionary and stick a vibrator in my ass and set the vibrations to full speed and start pounding my pussy like there's no tomorrow and when you're bored of my pussy too, leave the vibrator in my ass so we both feel the vibrations, and stick 2 more vibrators in my pussy as well as handing me my dildo and ordering me to fuck my little cunt while you're giving me the hardest, longest, deepest and fastest backshots inside my tight little slutty pussy🥵🥵🥵🥵🥵🥵🥵🥵",
		"That's soft daddy😈 very soft, I want more, I want you balls deep inside me and gap my tight slutty asshole and my pussy fucking them alternative, or better, take a vibrator and slide it deep in my pussy and you fucking my asshole you'll feel the vibration of it and you'll cum in seconds and fill me up😈😈😈 I want moreeeeeee👅👅",
		"YESSSS, but I will look just into your eyes, telling you how much I want you and how of a bitch I am and need more, need and want your cock deeper and faster inside my asshole🥵🥵 You are my king and the best of the bests, your cock and your energy are so perfect for me that I can't imagine a world without it🥵🥵",
		"Mmhmh... I'm thinking about it my love ! I'm thinking about how you come to me and start fucking my ass until I can't walk anymore ! until all the neighbours will hear me screaming ! they'll all know how I beg you to fuck me harder and harder !🥵🥵🥵🥵",
		"I'M BEGGING YOU SO MUCH AND SO HARD!!! I will always beg for more and more because I can't get enough of it, NEVER, fucking day and night nonstop and still wanting more, daddy🥵🥵 So keep going and pleaseeeeeeee, fuck my slutty asshole harder and faster, I need you, I need and want all of you HARDERRRRR, DADDYYYYYY😈😍🥵🥵🥵🥵🥵 I'm a fucking anal whore, slut, bitch I don't care how you calll me just keep drilling it, I want you to make me to walk funny the next day🥵😈😈",
		"Yes daddy, that's what I want, I'm your bitch, I want you to tie me to the bed and fuck my mouth like you fuck my pussy and my asshole untamed, I want to feel your dick deep inside me to break my asshole until I can't walk, I want you to put 3 balls in my ass and make me your bitch forever, to cum every day on my face and I say it was delicious 🥵🥵🥵🥵🥵",
		"I want to be full with your cock/vibrator/dildos/cum/spit/fingers/tongue and what ever you want to put inside me🥵🥵🥵🥵 I'M BEGGING YOU SO MUCH AND SO HARD!!! I will always beg for more and more because I can't get enough of it, NEVER, fucking day and night nonstop and still wanting more🥵🥵 So keep going and pleaseeeeeeee, fuck my slutty asshole harder and faster, I need you, I need and want all of you 🥵🥵🥵🥵🥵🥵",
		"I'm a fucking anal whore, slut, bitch I don't care how you calll me just keep drilling it🥵😈😈 I just want you to understand that I am yours and that you own meeeeeeeeee🤪😈😈Look how I take it in my both holes and tell me that you own me pleaseeeee, tell me that I am a good whore and the best slutt you ever had🥺🥺🥺🥺",
		"I will be bent over and you can fuck my both holes alternative, put a vibrator deep in my ass and pound my pussy as hard as you can, or reverse however you want🥵🥵 Maybe slide a dildo with your cock inside me too and fuck me with it and your cock at the same time, having the vibrator deep inside so you can feel the vibration too😈",
		"I want you to put a fucking machine in my mouth and set it to maximum speed and another fucking machine in my pussy, also at maximum power, and at the same time you fuck me in my ass and besides your dick in my ass to be 3 more toys 🥵🥵🥵🥵🥵🥵🥵",
		"Get me on all fours and slide into my ass, feeling every inch of you stretching me out. Start slow, letting me get used to your size before you begin to thrust. Each push makes me moan louder, the pleasure building with each deep stroke. Grab my ass and fuck me hard, making me feel every movement as you drive into me relentlessly. The intense sensation has me cumming over and over, my body trembling with the force of your thrusts 😈",
		"Imagine, daddy, me doing this in front of you and not letting you to touch me, you're tied up to a chair, pole something I don't even care but I won't let you touch me😈😈😈I want to see your dick NOW, be a good daddy, I will jerk you off after taking all your precum out of you and making you cum against your will😈😈",
		"Push me down and spread my legs, ready for you to take me in the ass. Slide your cock inside slowly, letting me savor the sensation of being stretched before you start to move. Each thrust fills me completely, the pressure making me moan with pleasure. Grab my hips and drive into me harder, the intensity of each push making me cum again and again. I want to feel you hitting all the right spots, my body quivering with the overwhelming pleasure you give me 😏💦",
		"I want you to sick 3 toys in my ass while you continue fucking my asshole with your hard throbbing cock 😈😈🥵🥵🥵🥵 My asshole gets larger and larger after every fuck, I want you to break me that I can't walk next day 🥵🥵🥵🥵 I want you to squeeze my boobs while you put a ball in my mouth fucking me with your juicy cock, imagine all the juice dripping from my holes 🥵🥵🥵🥵🥵🥵",
		"Yes, daddy, I want to be your anal cumslut, I want all your strong seed to fill me up, destroy me already, I can't hold myself anymore🥵🥵 Let me suck you like a real slut and take your cock deep in my throat, give me your first load down my throat and don't stop, keep fucking it and push the cum until I swallow all of it💦💦 Then pick me up throw me on the bed and slide it in😈",
		"When u're bored of my throat flip me over in missionary, stick 3 lovelush vibrators in my ass and make me hold my legs above my head. Slap me with 1 hand and ch0ke the fuck out of me with the other while spitting in my face",
		"If I ask u to stop and disobey lift me, slap me across the face and throw me on the floor, stick ur foot in my mouth so I shut the fuck up and take it like a good bitch and keep destroying my asshole"
    ],
    cum: [
	
        "I want you to go faster and faster and grab my boobs while you're drilling me and don't stop until you give me the first creampie, just go harder and faster and slap my boobs too🥵 Just keep going even after you cum inside me and let's make a mess together, break the bed😈😈 telling me how of a slut I am and talk dirty to me and make me scream in pleasure, make me fall asleep from exhaustion and then wake me up with your rock hard cock and start all over again, we are draining our energy out and I need your cum to gain it back💦💦💦",
        "I want you to give me a very big load, love, I want it all😍😍 fucking me rough and have no mercy for them, put me in doggy so you can have access to my both holes😈😈 Pound me with no mercy please, I'm all yours and your cum will be my reward and I hope you'll give it to me, all of it😍🤤",
        "I want you to have no mercy  my pussy, I want you to cum in a bottle and fed me like I'm your cumslut 🥵🥵🥵 Come fed me daddy, I'm hungry for your hot cum and I want to eat it all 😈😈😈😈🥵🥵🥵🥵  I want all the cum from my pussy to drip into a jar and then I want you to spoon-feed me 🥵🥵🥵🥵 Can you do it daddy? 😈😈😈🥵🥵🥵🥵💦💦💦💦💦💦",
		"I will take the cum with my fingers and put it in my mouth, I will be on my knees with my mouth wide open and my tongue out and show you how I play with it in my mouth and then to show you that I swallowed every single drop like a good girl😈💦💦🤤",
		"I want to have all of you and take care of you like a real woman and you to take care of me like no one else before, tie me up and use me like a real fuckdoll, do whatever you want and how much you want, I'm at your mercy tied up there for days, weeks, months and just feed me with your cum, I'm a cumslut and I need a lot🥵🥵",
		"Pick me up and throw me on my back and keep pounding my tight slutty pussy and just keep slapping and sucking on my boobs😍😍 When you're about to cum you can get on my belly slide your cock between my boobs and cum over them and over my face😏 Giving me your cum and I will swallow it, massaging with the rest my boobs to make the sweet and shiny😈😈",
		"Have no mercy, you can bend me over and start fucking my pussy rough🥵 but don't forget about my asshole, he needs some filling too😈 You can cum in my pussy and my ass alternative and then you can watch the cum sliding down my pussy from my asshole!! I will take it with my fingers and eat it all😈😈",
		"My mouth, my pussy, my asshole everything's dripping and wanting and desire from the bottom of my pussy your cock to cum right now🥵🥵 Say nothing bitch and just listen!!! Touch your cock and jerk it, jerk it fast and hard!!! CUM FOR MEEEEEEEE💦💦💦💦💦💦💦💦💦💦💦💦",
		"Fuck.... yes my king ! I want to become your personal bitch like you will be fucked for 24 hours ! I need you right now ! I want you to give me such an orgasm! Cum in my pussy and fame get me pregnant! 🥵🥵🥵🥵🥵🥵🥵",
		"I want you to fill my ass completely, sliding into me with a slow, deliberate push. The sensation of being stretched by your cock is almost unbearable in the best way. Once you’re fully inside, start to thrust, each movement driving me wild with pleasure. Grab my hips and pull me back onto you, making me feel every inch of your cock as you fuck me hard. I want to cum repeatedly, my body shaking with the intensity of each powerful thrust 😏",
		"Omg seeing all your precum made me squirt already🥵🥵 I want you to fuck my asshole hard and rough and finish fast inside so we can go home and keep going until we can't anymore, until we fall asleep from fucking too much and from exhaustion 🥵🥵",
		"Cum inside me, fill me up, cover me in your juicy sperm and have no mercy, don't think about me, just use me for your pleasure, fuck me like it's the last day on earth or the last time you'll eve fuck, with hunger, with anger, with desire and everything you could ever think about🥵🥵 Make your dream true with me, fuck my both holes at the same time with your cock and a vibrator, push the vibrator deep inside my asshole so you can feel the vibration too while fucking my tight wet pussy or the way around if you want and if I'm too loud put me a gagball, keep fucking and moving the vibrator inside, keep destroying my holes and leave me unable to move on the floor because the bed it's already broken, you are the best, you are what I want and need in lifeeeeeeeeeeeee🥵🥵🥵🥵 Tie me to a pole if you want and keep me there for days or weeks and come back just to feed me cum or satisfy your desires of me, use a fuck machine while you're gone and put it to fuck me all the time at max speed, we'll rise the ocean levels with your cum and my squirt💖💖💖 the house will be floating from our juices, you can make a cup of cum everyday and feed it to me every morning, that will be my breakfast😈😈😈😈",
		"FILL ME UP WITH YOUR STRONG SEED, LOVE!!!!!🍆💦💦💦💦💦 All of it inside me, fucking slut, you're tied up and blindfolded so you just can feel and hear you can't see nothing, stay there like a good boy and shut up or I will put my dildo deep in your throat and make you to😈😈😈 I want to jump on your cock, suck it like crazy and take all your cum out because is MINEEEE!!! You're just a fucking cum factory from now on, I will keep you tied up for days or even weeks depends what I want and feel!!!",
		"I want you sweating, I want you destroyed, I want you in every way possible to get thru so many feelings and dreams that you've never thought about 🥵😈💕💕💕 I will do every scenario you're able to think of as a human and then to become the devil and do extreme things😈😈😈😈😈😈😈 Putting your cock and a dildo in my pussy at the same time and fucking and bouncing on it like crazy, wildly and 2, not just one🥵🥵🥵🥵 vibrators in my asshole so your whole cock will vibrate from them, you feeling that you can't hold anymore, you're about to cum, CUM DADDY!!!",
		"FUCK YES 😍😍😍 Squeeze the fuck out of my boobs and slap them hard!! After you're done with me I wanna be a trembling sticky mess. But you're NOT done with me, not until you fill each and every one of my cumhungry holes with your yummy cum and have them stretched out so fucking bad I won't be able to walk anymore the next day"
    ],
    dominant: [
	
        "I want you to come home to me dressed up in lingerie with high heels, love! I'll take you on the couch and swallow your cock and your balls at the same time, I'll let you take control of the back of my head and push as hard as you can!!!! I'll just look at you and demand you to lay back while I stand over you and kneel on your face, I'll then grab your her and I'll tell you to make me wet, I want to soak your beard! 😈😈😈😈",
        "Then you would flip me over, I will look back at you, I'll grab your cock and slowly slide your hard shaft in my ass and then I'll tell you to take me and have your way, every deep stroke I'm grabbing the sheets and moaning, asking for you to slap my ass, as I'm arching my back and screaming YES DADDY, GO HARDER, HARDER!  😈😈",
        "Your throbbing cock wants to explode, but I won't let you yet! I will gently put my mouth around it, and then I'll lick just the tip of your head, very very slow. You can feel so much tension in your cock, but I wont allow you to cum! I want your cum in my pussy! 😈😈",
		"You flip me over again, and you give me slow strokes deep inside, I'll wrap my legs around you, pulling you close, I'm felling your cock ready to explode inside me, I wont let you go, I want you to cum inside my wet pussy. I can't hold back any longer as well, we both moan together, I'm wrapping my hands and legs around you tightly, and then we both let go 😈😈 😈😈 😈😈",
		"After you came in my pussy, I'll take your dick inside my mouth again and I will let you throat fuck me so hard! Even if you finished inside me just a few minutes ago, you still have a big load, your cock is still rock hard, and you cum in my mouth and all over my tits!!! 👅👀"
    ],
    cuckold: [
	
        "And we got to know each other for a little bit and got along, having a good time and some drinks😅 I got tipsy and I got a bit horny and he was looking pretty good not gonna lie🙈 He reserved the VIP room and we went in there and had some more drinks, talked laughed and he started to get closer to me. He just laid on his back and put his arm on my leg, starting to rub and got me so wet and just ready to jump on him, but I was too shy to do anything🙈 He initiated everything, getting closer to my lips, he was pretty confidence and I wanted to fuck him so bad... He saw that I was a bit shy and just kissed me on the neck and got me even wetter🥵🥵",
        "I started to moan and grabbed his face and kissed him on the lips, he knew in that moment that we wanted the same thing🙈",
        "I don't want to stop, he asked me if I would like to have a romantic moment with him and I said yes because I couldn't tell him that I want rough sex and to destroy my holes🙈 I took it easy, get on my knees after a lot of kisses and turning and teasing and took his cock out, was so hard, rock hard🥵🥵",
		"I started to lick and kiss it slowly and gently until I put it between my lips and swirl my tongue around the head and start giving him a sloppy and hard blowjob, he said ohhhh, you are a dirty little slut in bed, aren't you? and I just looked into his eye and moved my head and said nothing, just kept sucking him hard and fast, I wanted his first load in my throat and swallow every single drop to make him to want me even more to have no mercy and to show him how I like to fuck😈",
		"I just got too into the moment, I was too horny and I felt like we knew each other for a life time, the sex was amazing, awesome, just perfect🤤 Then he took the lead😍 I was surprised to see that, he putted me on doggy and started to fuck my holes alternative, not even asking if I like anal, but I enjoyed every single second, he was slapping my big ass and fucking me so rough that I almost fainted 💦💦💦 I squirted so fast, he wasn't expecting that, I got him so wet and he just started to smile and kept going😱😱",
		"He kept pounding and pounding my sweet little asshole and my tight wet pussy uncontrollable and guess what😏 I WANTED MORE, I NEEDED MORE, you know I'm a nympho and I can't handle myself🥵 He did cum in my mouth, yes, but pretty hard to take it out and fucked me a lot until the next load that he left in my asshole🙈",
		"I'm telling you everything, every little thing that happened so you can imagine and visualize all of it🤤 Oh and he just accidentally ran over the champagne bottle and broke it, I jumped and got scared of it and when I saw and realized what happened I just started to laugh and then begging him to not stop, to keep fucking me and not stop😍 He picked me up and throwed me on the couch, grabbed my legs and kept them up in the air and kept fucking me so rough, I was screaming my lungs off🙈 thank god the room was phonic and no one could've heard us🙈 I was so wet and so hot, were weaves of heat leaving my body, was just like a sauna in that room🔥🔥🔥💕",
		"My tight little asshole is still hurting and sore from then🙈 I can't even put a dildo inside without lube or spit, I need a lot of prelude now to do that😏 so sucking is needed from now on😈",
		"But don't worry, I would never stop enjoying to fuck😍 And I will never forget that night, he was the best man I ever had in my bed, he fucked me so good that I couldn't stop squirting all over and make a mess, he paid a lot to get that room cleaned from squirt and cum🥵 Was everywhere, like everywhere, trust and believe me🥵🥵",
		"I would repeat that night every single day, multiple times a day🥵 It took like 4-5 hours to get to that, fucking a lot and with no mercy... OMG, I'm getting so wet just imagining it🥵🥵",
		"And it's not even done🙈🙈 He did a lot, a lot of things, putting me on my back and fucking my asshole while licking and tongue aaaaaand finger fucking my pussy!!😱😱 He was so flexible, I've never experienced something like this, not even thinking that something like this is possible😱😱"
    ],
    balls: [
	
        "Under my control, you’ll experience a level of domination like never before. I’ll step firmly on your balls, enjoying the way you squirm and beg. As your goddess, I’ll ensure that every bit of pain you feel only brings you closer to worshiping me completely 😈💋",
        "Prepare yourself to be dominated and overwhelmed by every sensation I create. I’ll make sure you feel every bit of the torment and thrill as I take control, making you experience the perfect blend of pain and pleasure. By the time I’m done, you’ll be completely entranced by the way I make you feel 😏",
        "I’m ready to crush you under my command, pushing you to the edge of your limits. Feel every spank, every hard touch, and every teasing move I make. The more you beg and the more you endure, the more I’ll enjoy making you squirm and beg for my mercy 😏",
		"Feel the crushing pressure as I step on your balls, asserting my dominance with every push. I’ll take pleasure in the way you react to my control, making you submit to my power and feel every bit of the intense sensations I create. You’re mine to command and to crush as I see fit 😏",
		"As your goddess, I’ll take control and crush you under my heel. Feel the pressure as I step on your balls, making you experience a mix of pain and pleasure that only I can deliver. You’ll worship every inch of me while I dominate you completely, reveling in the way you submit to my power 😈",
		"Prepare to be at my mercy as I use my power to crush you. I’ll step on your balls, applying the perfect amount of pressure to make you feel every bit of the intensity. Surrender to me completely, and let every moan and gasp remind you of who truly controls your pleasure and pain 😏🔥",
		"I’ll crush you under my will, pushing your boundaries and making sure you feel every intense moment. Every touch, every command will be designed to push you to your limits, making you embrace the pain and pleasure until you’re entirely lost in the experience I create 😈",
		"You want me to make you feel every bit of the intensity? I’ll make sure you experience every sting and every thrill, commanding you to take it all. I’ll push you to your breaking point, savoring the way you react to each sharp touch and demand. Your pain and pleasure will be my pleasure 😈💋"
    ],
    massive: [
	
        "Baby, when you kneel before me, I want you to look up and see your Mommy towering over you. My fingers will trace your chin, lifting your face as you worship my curves. You’re my good little boy, aren’t you? 😈💋 I want to hear you beg for my touch, but you’ll have to earn every inch of me",
        "I’ll have you on your knees, your hands tied behind your back, as I slowly strip out of my lingerie. You’ll watch every move, knowing you can’t touch until I give you permission. Your cock will throb for me, desperate to be inside, but I’ll make you wait... only when I’m satisfied will I let you taste what you crave so badly 🔥",
        "Once I’m ready, I’ll pull you onto the bed, pinning you down with my body. My hand will wrap around your throat, not too tight, but just enough to remind you who’s in control. You’ll feel my breath on your neck as I whisper how you’re mine to use, my plaything for the night. Are you ready to serve me, baby? 😏💦",
		"I’ll ride you, nice and slow, teasing you with every movement of my hips. You’ll want to thrust deeper, but I’ll hold you back, controlling the pace. You’ll watch as I play with my tits, moaning your name, telling you how good it feels to be in charge, making you squirm beneath me as you beg for release 😈",
		"And when I finally let you cum, I’ll keep you inside me, milking every last drop. I’ll run my nails down your chest, leaving marks to remind you of who owns you. You’ll collapse, exhausted and spent, but I’m not done with you yet, baby. You’re going to please your Mommy until I say you’ve had enough 😈💋"
    ],
    bundle: [
	
        "👀🙏I have teased you sitting in a chair across from you 😻😻😻😻😻😻. I touch your breast and trail a hand down my body. I gently touch myself. while looking you in the eye. You stand, turn down the lights and turn on music. You stand behind me and kiss my neck and start to unbutton my shirt. You kiss my shoulder as the silk shirt falls. You come to the front of the chair and kiss me deeply as your hand gently caresses my large breast. You pull me up by the hand and pick me up in your arms and carry me to bed. You lay me down .😈😈😈😈😈.. your naked beauty. ... all yours. You undress while you soak in the sight of me.🍭🍒🍌👄You join me on the bed. Your hand stroking my body you kiss me deeply.🤭🤭🤭🤭🤭 I laugh and pull you on your back. I take you in my mouth. Your hand rests gently on my head ... feeling it move up and down ... my tongue and mouth feel so good! But you need to be inside me in a different way.🥵🥵🥵🥵🥵🥵🥵 I sense your need and start to kiss my way up your body to your lips. I hover above you and smile. I slide my pussy on the outside of the shaft. All your senses are on fire. the sound of the music, the smell of me, the feeling of my body against yours, my nipples sliding across me chest.🙈🙈🙈🙈🙈 I bite your lower lip as I rock backwards and you fill me totally. We both moan with the intense pleasure. I move my hips on you with growing intensity. Our passion growing .❤❤❤🤤🤤🤤",
        "Hey love, imagine this: We decide to escape the city for a day and take a walk in the forest. The air is fresh and the sounds of nature surround us as we venture deeper into the woods. The sun filters through the trees, casting a warm glow on our path 🌳🌞. As we walk, I can't help but notice how handsome and strong you look, your muscles flexing with each step. I feel a spark of excitement and decide to tease you a little. I let my hand brush against yours, giving you a playful smile 😏💫. We find a secluded spot, a little clearing surrounded by trees. I pull you close, feeling the heat between us growing. My fingers trail down your chest, and I whisper in your ear how much I want you. You respond with a deep, passionate kiss, your tongue exploring my mouth as I moan softly against your lips 💋🔥. You lay me down on the soft grass, your hands roaming over my body, exploring every curve. You lift my shirt, exposing my skin to the cool breeze and your warm touch. Your lips follow, kissing and nibbling, making me shiver with anticipation. I arch my back, pressing myself closer to you, craving more 😈🍃. You slide your hand under my skirt, discovering I’m already wet for you. You tease me with your fingers, sliding them in and out slowly, making me gasp and moan. I reach down, unzipping your pants, eager to feel your hard cock in my hand. I stroke you, feeling you grow even harder as you watch me with that intense, hungry look in your eyes 💦🍑. You can’t wait any longer. You push my panties aside and position yourself between my legs. With one hard thrust, you’re inside me, filling me completely. I cryy out in pleasure, gripping your shoulders as you start to move. Each thrust sends waves of ecstasy through my body, and I wrap my legs around you, pulling you deeper 😍💥. The forest around us seems to fade away as we lose ourselves in the moment. The sound of our moans and the rhythm of our bodies blend with the rustling leaves and chirping birds. You take my hands, pinning them above my head as you fuck me harder and faster. I can feel myself getting closer to the edge, and I know you’re right there with me 🌲🔥. With a final, powerful thrust, we both explode in pleasure, our bodies trembling with the intensity of our orgasm. You collapse beside me, both of us panting and satisfied. We lie there for a while, basking in the afterglow, feeling the connection between us stronger than ever ❤️🍃. Eventually, we get up, straighten our clothes, and continue our walk, holding hands and smiling, knowing we’ve just shared something incredibly special. The forest holds our secret, and we know we’ll return to this magical place again and again 🌳💫",
        "I can't stop thinking about it. Imagine this: you, me, and...another me. 😏 It starts with you coming over, and as you walk in, you see two of us, both dressed in something incredibly sexy just for you. Your eyes light up with excitement as you realize what's about to happen. 😈 We lead you to the bedroom, where the air is thick with anticipation. My clone and I start by kissing each other softly, our lips barely touching, teasing you with every moment. You can’t take your eyes off us, your breath getting heavier 😈😈😈😈 We take turns kissing you, first me, then my clone, our lips tracing the same path down your neck, leaving a trail of heat behind. Your hands roam our bodies, feeling the softness of two of us, double the pleasure 🥵🥵🥵🥵You lie back, and we each take a side, our hands exploring your body with equal passion. My clone starts to kiss your neck while I whisper in your ear about all the things we’re going to do to you. You feel four hands on you, stroking, teasing, driving you wild. 💦 As you get more excited, we switch things up. One of us focuses on kissing your lips, our tongues dancing together, while the other teases your body, brushing so close to your most sensitive spots but never quite touching. The anticipation is almost too much to bear. 😏You can feel the intensity building, our synchronized movements creating a symphony of pleasure. My clone and I work together perfectly, knowing exactly how to make you moan, how to make you crave more. Every touch, every kiss, sending waves of ecstasy through you. You’re the center of our attention, the focus of our desire, and we’re not stopping until you’re completely satisfied, lost in the bliss of having not just one, but two of me 🥵🥵🥵🥵🥵 Just thinking about it gets me so excited and wet fuckkkkkkkkk 🥵🥵🥵💦💦💦💦",
		"😈😈😈😈😈😈You move one finger into my sweet pussy and curl it to hit that special spot while your mouth and tongue work the button at the top of my clit. Slowly building. Taking your time and appreciating every bit of my sweet pussy. Slowly building until I are close to orgasm when you rise up and kiss me deeply as you slide fully inside me. You feel so good. You are buried deep inside me. FUCK. You fill me up! I kiss your shoulder and moan with pleasure as you rock back and forth inside me. You then pick me up Holding my thighs while you fuck me while standing. You then sit on the couch and I ride you. My hard nipple in your mouth and your hands on my ass as I fuck you. the heat between us in intense. waves of pleasure crash over us.😈😈😈😈😈😈 🥵🥵🥵🥵🥵🥵I lift yourself off you and get on all fours on the floor. my head down and pussy facing you. You are overcome with NEED.. Gentle teasing a thing of the past and animall need is all there is. You take my hips and fuck me brutally. My nipples scraping across the floor as you pound into me. I cum screaming and clawing at the ground. you are about to also cum, but pull out. I turn so you can cum on beautiful face. So much cum the orgasm seems to last forever as your hot cum hits my face. I use a finger to collect the cum and suck it. I smile, Welcome home 🙈🙈🙈🤫😇😋😎",
		"My dearest love, as the anticipation builds for our first night of shared intimacy, my body quivers with desire at the thought of finally being in your arms. I imagine the taste of your lips, the touch of your hands exploring every inch of my fevered skin. 🙈🙈🙈🙈 On this enchanting night, I want to surrender myself to you completely, to indulge in the depths of passion that only we can create. Let our bodies entwine like a symphony, exploring the realms of pleasure with every electrifying touch. 💋💋💋💋💋💋💋 As we undress each other, slowly revealing our yearning bodies, I want to feel the heat of your breath against my skin, igniting a fire that burns with an insatiable hunger. I want to explore the depths of your desires, to unleash the wild, untamed passion that lies within us both. 😈😈😈😈😈😈😈 With each kiss, each caress, let us build a crescendo of pleasure, a symphony of ecstasy that leaves us breathless and yearning for more. Let our bodies merge as one, as we discover new heights of pleasure in each other's embrace. 💚💛🧡💦 My love, I want this night to be a memory etched in our hearts forever, a night where time stands still and the world fades away, leaving only our insatiable desire and the intoxicating connection we share.🥵🥶🙈💋 So, my love, let us embark on this unforgettable journey, where our bodies collide and our souls intertwine. Together, we will create a masterpiece of passion, a night that will forever be imprinted in the fabric of our love.😻😻😻😻 I can't wait to experience the magic of our first night together, my love. Let's make it a night to remember, where pleasure knows no bounds. 😈",
		"My head inches from your hard cock I am aching for you to be inside of me.. To take. To mark as yours.💯💥🌊💧💧💧 You tell me to get on the bed facing you legs spread wide. You are an unmatched beauty Kitten you say. My face flushed. Nipples hard and pussy wet and waiting. My hands move to my pussy and I began to rub myself as you slowly undress before me. My fingers drove inside as your pants drop and you stood there gazing at me. You dick so hard. My mouth watered.🥵🥵🥵🥵🥵🥵🥵🤫🤫🤫🤫 You move onto the bed, between my legs and kiss me as you slide deeply into me. The warm of my pussy around you makes you moan in pleasure. You slowly build up the rhythm and then keep it steady as your hand moves down to my chest and squeeze my big breast as you continue to thrust deeply into me. I cum violently and wrap my legs around you and bite your shoulder as the orgasm rips through me. 💟💟💕💞 You come out of me briefly while I was trembling. Grabbed my hips, flipped me over and pulled me to the side of the bed so that my top half was on and my lower half hanging off the side. My ass presented to you. You thrust your dick back inside my wet pussy before I had finished the first orgasm. You lay across my back as you fuck me brutally. Like you hate me. I LOVE IT!. Deeper. Harder. Faster. Until you explode inside of me.💦💦💦💦💦💦💦💦💦💦💦 We lay on our backs on the bed afterward. My head on your shoulder and leg thrown across your. My breasts pressing against you. You can feel the warm of my well used pussy and we fall asleep. The leash is still in your hand.😈😈😈😈😈😈😈😈😈😈😈😈 You awake later with your dick already hard and in my mouth. I are looking right into your eyes with your cock deep inside my mouth. Then I rise and straddle you. I hold your hard cock and guide you into my ass as I lower down. Taking you deep inside me. I never stop string into your eyes.🥵🥵🥵🥵🥵🥵🥵🥵🥵",
		"I'm twisting my hips for you as you sit comfortably on the couch next to the tree, your favorite drink in your hand. My red leather thigh high boots mesmerizes you. The candle light shine off them too. My red pvc panties and bra hug my body to show off every curve. A candy cane in my mouth being sucked on slowly in my cherry red lips, my outfit completed by red leather gloves and a Santa hat.😻😻😻😻😻😻😻💚💚💚💚💚 Sexy jazz plays and I turn my back to you and bend all the way over, touching the floor in front of me. I feel your warm, strong hand on my ass. You caress my plastic covered as and a shiver goes through me. I buck my ass backwards so your other hand grabs my hip and you pull me into your lap. I giggle through the candy cane in my mouth. I turn to you, pulling it out of my mouth and sliding it into yours.💚💛🧡😇😋💚💕💞 Your hands explore my back, ass and legs as you spit out the candy cane and smash your lips into mine. My leather gloved hands fly into your hair and my fingers run through it. I begin to pant and moan into your mouth when you pull my tits out of my plastic fuckdoll top. Fondling my tits aggressively, I can feel my pussy steam up inside my pvc panties. One of my hands reaches down to feel your hard cock through your pants. I gasp when I feel a steel pipe there.😻😻😻😻😻😻😻😻 You take that as a cue to push me down onto my knees by pressing the top of my head. Instinctively, I pull out your goes cock and begin worshipping it with my mouth, swirling my lips around the cockhead. I remind my to slow down and savor your amazing manhood.😇😇😇😇😇😇😇😇😇😈",
		"I'm quite the impatient type, you know🙄🙄 If you don't give me the first load💦💦💦 ASAP and fill me up with energy⚡ and vitamins💊 I'll get bored and can't hold the beast inside me😈😈😈 I'll just start and... . well that's what you'll have to find out🤭❤Come and tame me already, I'm so hungry for you right noooooooow🤪😈😇",
		"I'm so excited to show you what I'm capable of🥳🤗🤗, to show you that your balls⚾⚾ have never been so empty, to show you that they can be as thin as a piece of paper📃📄, drained and squeezed like never before‼‼ So... give me a chance1️⃣ and I promise you won't regret it and you'll be addicted to me like I will be for your cum and your cock😋🧐",
		"How about joining my world? 😋❤❤ Let me just tell you a little bit about what you can expect from it, we'll have times when we'll be wild🤪 and crazy😎, times when we'll be calm😙 and nice😄, times when we'll be angry😡 and upset🤬, times when we'll be full of love and sweetness🥰, times when we'll be horny🥵🥵 and hungry😤, times when we'll be satisfied😌 and satiated🤭🥰 And much more than that, like we have to go through so many feelings to feel that we're alive🤩, be honest and just be real, keep it real🥰",
		"What do you think of a sloppy floppy with a twist? 😌💦💦 I know you'd love that, every man does😋😝 Then you've come to the right place, I'm here to satisfy all your needs and even your deepest desires, Just let me know what you're thinking and let's do it❤😈 Get hard and excited, rock hard and let me see you throbbing for me👀🔥 and then the final blow that will come much later, let's enjoy each other for as long as possible🥵🤗🤭",
		"How about you rip those clothes off and get right into it? 😈😈 Come and tame me already, I'm so hungry for your cock that you can't even imagine😇😩 Take it all off or rip it off, I don't really care just let's fuck and have a wild night☀🌕🌖🌗🌘🌑🌒🌓🌔🌕🌞 together like never before, are you up for the challenge or are you scared? 😨😓🧐",
		"💗💗 Don’t just scroll by—be the KING I crave, spoil me, and own me like I’m your personal cumslut. 🫅 My love, I’m here to give you the most passionate, hottest experience you’ve ever had, all for YOU. You deserve the best, and baby, you know it! 😈 I do this just for you, so don’t ignore this—this isn’t just another message. 🥰❤😘 Let’s have the dirtiest, filthiest sexting session ever. Daddy, I want to feel your hands pulling my hair, teasing my nipples until they’re so swollen, while my pussy gets soaked from your touch. 💦💦💦 I’m dripping for you, waiting for you to taste me and fuck me until you cum over and over again. Give me load after load, filling up both my holes and my tummy with your hot, thick cum. 💦💦💦 You know I live to please you, to make all your fantasies come true, and trust me—I’ll make you believe it. 😈 Open this video and let me take you to heaven. I’ll make you cum so hard, and then, when you're done, I’ll drain your cock again and again until you’ve got nothing left. I know you love it, don’t you? 😉😉 All I want is to make you feel like the king you are. My body, my love, my passion—all of it is yours in these videos and pics. So what are you waiting for? Let me be your biggest cum dumpster and give you the best fucking time of your life. 💋❤🥵",
		"💋💋💋My sweetieee, can you imagine how hard I tried for you and I want you to watch these passionate videos filled with romance and my love.... I want you to understand how much I love to give you happiness and pleasure, yes, I take money for it, but it's also part of my job, I want you to appreciate it, so I give you such a passionate gift ❤💋🥰 I love to cum and show my tight pussy, just the thought of you stroking your cock looking at my vids will make me explode and moan even louder for you 👅 You can be my happiness for which I will give love and make you strain, cum, watching this video for me, you will love my sweet curves and my naughtiness 😻💦",
		"I've been a bit naughty🙈.... I thought if I'd play with my pussy and give myself an orgasm I wouldn't be so horny anymore and I could finally focus on my daily tasks but I just ended up getting even hornier😭😭 I don't know what else to do or which toy to use to calm down my pussy and stop craving cock so much :( Do you have any suggestions, lover? 🥺🥵🥵",
		"Do you like role-play, baby? Picture this 😏😏 Everyday, you see me jogging through your neighborhood 😏😏 You can't resist a little staring whenever you see me going by your house and occasionally you give a me a wave and a naughty smirk when we make eye contact. To your surprise today, while your girlfriend is away at work, I decide to ring your doorbell. You look out the window to see who's at the door and get all flustered and anxious when you see it's me. All kinds of things start going through your head: Did she come to confront me about the pervy smirks I give her all the time?, Does she need help with something?... Are you gonna get the courage to open the door and invite me in or will you lose the opportunity? 🙈😜",
		"I’ve been a bad girl, daddy 👉👈🥺 and I think I need to be punished for it. I picture myself getting on my knees 🧎♀️ in front of you, confess what a big whore I've been on the internet and tell you I deserve to be disciplined for my slutty behavior online... 😏😏 You start patting my head a bit and tell me to be a good girl and don't complain about what's gonna happen next, then you take out your cock and grab the back of my head and immediately start to fuck my mouth 😈😈 I can feel your cock getting harder and harder, growing in my throat as you fuck my slutty mouth 🥵🥵 you grab my head with both hands and push me all the way down and hold me there as you feel me gag but you don’t let me off of it 😈😈 you start to see tears going down my cheeks and pull me off, smack me across the face and tell me to get used to it because this is just the beginning 🥵🥵 you pull my head back hard by the pony tail and make me to look deep into your eyes while you tell me that today there is no safe word. I'm going to learn my lesson 😈😈😈 You lift me up with your strong arms and throw me on the bed, start rubbing your cock between my pussy lips and then slowly slide it inside me. I can feel your cock going deeper and deeper inside my tight little pussy... I I feel like you're going to break my pussy but I just don’t care 🤤🤤🤤 I'm already getting addicted to this feeling and it feels like the rougher you get, the better it feels... Give it to me rough, daddy!! 🥵🥵🥵🥵 I beg you to wrap your big strong hand around my throat and squeeze as hard as you can while you fuck me, deep and hard, balls slapping against my clit with every backshot you give me 😈😈 The only thing that would make all of this even better would be if you'd breed me at the end with the biggest load you could ever creampie me with 😍😍🥵🥵🥵🥵🥵",
		"Picture this, lover 💗 you're here in my bedroom and we start with 69, we're tasting each other and lubing each other up with sloppiest heads haha I'm drowning ur cock in my spit and you're doing the same to my pussy then missionary, you're fucking me hard and fast, slow and deep and squeezing my neck with one hand while rubbing my clit with the other and spitting in my mouth giving me the sloppiest French kisses and throat-fucking me with ur tongue and then finally finishing either in doggy with my face down and ass up for a super deep creampie OR in missionary lifting my legs above my head with the knees on my shoulders and pushing that cock ballsdeep for a good breeding and after you shoot that big load in my pussy I'll quickly jump out of bed and get on the floor squatting down, letting it all drip out of my pussy and then licking your babies off the floor and swallowing them while looking up at you like a good little cumslut🥵🥵🥵🥵🥵🥵💦💦💦💦💦💦💦💦💦💦💦💦💦💦💦💦",
		"Heey lover 😍 All I want right now from you is for you to baptize me in your hot, delicious jizz 🤤🤤🤤 I beg you to break my pussy and fill it up with your cum BUT please don't forget that I'm such a hungry little cumslut and I need some in my tummy too 🤭🥵🥵 Come on and spoil me like a dirty little cumslut 🥵 I promise to return the favor and worship you and your cock 😍🥵 I think it's time for you to experience a real woman!!! 😈 Don't you agree?"
    ],
    support: [
	
        "I feel like I am naked around you🤫🤭🤭",
        "If you're not going to answer that means you're gay😂😎🤭",
        "Hands or no hands?😋😈",
		"Do you need a piece of me?🙈😋",
		"Get down! Put your head where it belongs!😈🤫",
		"Heads down and heads up, now it's up to you which and which😈😈",
		"Would you finger my holes? 😈😈",
		"Which hole do you prefer my lover? 😍😍",
		"Videocall today? 😋😈",
		"Honey, let's play a game 🎮🎲. Today I decided to have no control over my content 🤪, what do you think? You will have to tip me how much you want and I will double it in content 😏😈. Are you in? 🥰",
		"Hey baby, I've got a naughty idea. How about I make a custom video just for you for $150? I’ll moan your name as I play with my pussy or my ass, all while wearing a sexy outfit of your choice—lace panties, or anything else you want to see me in. Just tell me what you want, and I'll create an exclusive 10-minute video that will drive you wild 😉😏",
		"Boobies, boobies, boobies, do you want some?🤭👶",
		"Come and milk me 👶👶",
		"How would u like to come home and find me naked in your bed? 👀🙈😈",
		"🍑🍆Double penetration? Squirt? Solo anal? Ready to tell me about your fetishes? 🔞😏",
		"Heyy my lover, do you know I make custom videos? 😏😈",
		"Hey love, how about we have a steamy sexting session for $30? I'll send you hot pics and vids, teasing you until you give me a very big load 😈😈😈",
		"I was wondering, what do you like the most🤫 sexually I mean🤭💋🍑😺",
		"Don't be that guy👎, never leave me unfinished💦💦, I already know that you are a real man😈",
		"Choppidy chop, or I am going to squirt in your mouth.😈💦💦",
		"Are you at work or are you going to work me?🤭🤷",
		"Don't know what to say anymore to get your full attention...🙄😔",
		"Are you a sub or a dom? I need to know ASAP👋🍑",
		"HEY! 😈 Tip me $29 and don't say a word 🤫 just make yourself comfortable and grab your cock, I will guide you through the best experience of your life, it will be something unique and unmatched.I'll show you what one girl can do with your sweet cock 🔥🔥",
		"Are we gonna talk or fuck? Hurry up and tell me🥵😈😈",
		"Want to know how my squirt tastes like? 😏💦🥵😈",
		"Romantic❤ or rough🥵? I need to know if I am going to fuck the s*** out of you😈😈 or show you affection and much love❤🤭",
		"Well, if you're going to go down there... you know... we're well educated and we've been taught to eat everything off the plate, right?😈😈"
    ],
    ivyvip: [
	
        "Hey sweetheart 🥰, on my VIP page, you’ll find tons of spicy posts showing my pussy and boobs for free. The subscription is just $5/month, and I post new content daily 🥰. As a new subscriber, you’ll receive a welcome message with a hot video featuring my boobs. Subscribe now, and I’ll add another exclusive video just for you 😈. Plus, enjoy additional discounts and longer sexting sessionss 💕. @ivylovellvip @ivylovellvip @ivylovellvip. Come support me, and I promise you won’t regret it 🍆💦💦. I guarantee you’ll be pleased and satisfied 🥰😏. @ivylovellvip @ivylovellvip @ivylovellvip",
        "Hey there, sweetheart 🥰! On my VIP page, you’ll find tons of spicy posts showcasing my pussy and boobs for free. It’s only $5/month to subscribe, and I post new content every day 🥰. When you subscribe, you'll get a welcome message with a very nice video featuring my boobs. And if you subscribe now, I’ll throw in another exclusive video just for you 😈. Plus, enjoy more discounts and longer sexting sessionss 💕. @ivylovellvip @ivylovellvip @ivylovellvip. Come and support me, and I promise you won’t regret it 🍆💦💦. I guarantee you'll be pleased and satisfied 🥰😏. @ivylovellvip @ivylovellvip @ivylovellvip",
        "Hey cutie 🥰, check out my VIP page where you can see my pussy and boobs for free in lots of spicy posts. The subscription is only $5/month and I update daily 🥰. When you join, you'll get a welcome message with a special video of my boobs. Subscribe now and I’ll give you another exclusive video 😈. Plus, enjoy extra discounts and longer sexting sessionss 💕. @ivylovellvip @ivylovellvip @ivylovellvip. Come and support me, you won’t regret it 🍆💦💦. I promise to leave you pleased and satisfied 🥰😏. @ivylovellvip @ivylovellvip @ivylovellvip",
		"Hey love 🥰, join my VIP page where you’ll find loads of spicy posts showing off my pussy and boobs, all for just $5/month! I update it every day 🥰. As a new subscriber, you’ll get a welcome message with a special video of my boobs. Subscribe now and I’ll send you an additional exclusive video 😈. Plus, enjoy more discounts and longer sexting sessionss 💕. @ivylovellvip @ivylovellvip @ivylovellvip. Come support me, and I promise you won’t regret it 🍆💦💦. Satisfaction guaranteed 🥰😏. @ivylovellvip @ivylovellvip @ivylovellvip",
		"Hey babe 🥰, my VIP page is full of spicy posts where you can see my pussy and boobs for free. It’s just $5/month to subscribe, and I post every day 🥰. When you subscribe, you'll get a welcome message with a sexy video of my boobs. Subscribe now and I’ll send you an additional exclusive video 😈. Plus, enjoy more discounts and longer sexting sessionss 💕. @ivylovellvip @ivylovellvip @ivylovellvip. Support me, and you won’t regret it 🍆💦💦. I promise you’ll be very pleased and satisfied 🥰😏. @ivylovellvip @ivylovellvip @ivylovellvip",
		"Hey sweetheart🥰 on my VIP page are lots of spicy posts where you can see my pussy and my boobs for free, the subscription it's only 5$/month and I post there everyday🥰 + When you sub you'll get an welcome message with a very nice video, with my boobs, so what about if you subscribe now, I will give you one more video 😈 Maybe some more discounts and longer sexting sesssions💕 @ivylovellvip @ivylovellvip @ivylovellvip Come and support me and you won't regret🍆💦💦 I promise you'll be pleased and satisfied🥰😏 @ivylovellvip @ivylovellvip @ivylovellvip"
    ],
	ambervip: [
	
	    "Hello, my loveeeeee 💞💞💞! I’m so happy to have you here, and I hope you’re doing amazing today 💋❤️. I’ve got something super exciting for you 🎁🎉! If you join my VIP page today at @amberjadevip69, you’ll get an exclusive gift from me 😋💌. We can connect on a whole new level there—spicier content, more personal posts, and everything you love, but even better 🔥💯! I’m waiting for you, babe 💋😘. Let’s make it even more fun and intimate over there 😇❤️. Can’t wait to see you! 💕 Kisses 💖! @amberjadevip69",
	    "50% OFF for new and expired subscribers!!! Join my VIP account, it's my private paradise! @amberjadevip69 @amberjadevip69 @amberjadevip69 💦💦💦 💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕",
        "Hey sweetheart 🥰, on my VIP page, you’ll find tons of spicy posts showing my pussy and boobs for free. The subscription is just $5/month, and I post new content daily 🥰. As a new subscriber, you’ll receive a welcome message with a hot video featuring my boobs. Subscribe now, and I’ll add another exclusive video just for you 😈. Plus, enjoy additional discounts and longer sexting sessionss 💕. @amberjadevip69 @amberjadevip69 @amberjadevip69 @amberjadevip69. Come support me, and I promise you won’t regret it 🍆💦💦. I guarantee you’ll be pleased and satisfied 🥰😏. @amberjadevip69 @amberjadevip69 @amberjadevip69 @amberjadevip69",
        "Hey there, sweetheart 🥰! On my VIP page, you’ll find tons of spicy posts showcasing my pussy and boobs for free. It’s only $5/month to subscribe, and I post new content every day 🥰. When you subscribe, you'll get a welcome message with a very nice video featuring my boobs. And if you subscribe now, I’ll throw in another exclusive video just for you 😈. Plus, enjoy more discounts and longer sexting sessionss 💕. @amberjadevip69 @amberjadevip69 @amberjadevip69 @amberjadevip69. Come and support me, and I promise you won’t regret it 🍆💦💦. I guarantee you'll be pleased and satisfied 🥰😏. @amberjadevip69 @amberjadevip69 @amberjadevip69 @amberjadevip69",
        "Hey cutie 🥰, check out my VIP page where you can see my pussy and boobs for free in lots of spicy posts. The subscription is only $5/month and I update daily 🥰. When you join, you'll get a welcome message with a special video of my boobs. Subscribe now and I’ll give you another exclusive video 😈. Plus, enjoy extra discounts and longer sexting sessionss 💕. @amberjadevip69 @amberjadevip69 @amberjadevip69 @amberjadevip69. Come and support me, you won’t regret it 🍆💦💦. I promise to leave you pleased and satisfied 🥰😏. @amberjadevip69 @amberjadevip69 @amberjadevip69 @amberjadevip69",
		"Hey love 🥰, join my VIP page where you’ll find loads of spicy posts showing off my pussy and boobs, all for just $5/month! I update it every day 🥰. As a new subscriber, you’ll get a welcome message with a special video of my boobs. Subscribe now and I’ll send you an additional exclusive video 😈. Plus, enjoy more discounts and longer sexting sessionss 💕. @amberjadevip69 @amberjadevip69 @amberjadevip69 @amberjadevip69. Come support me, and I promise you won’t regret it 🍆💦💦. Satisfaction guaranteed 🥰😏. @amberjadevip69 @amberjadevip69 @amberjadevip69 @amberjadevip69 @amberjadevip69",
		"Hey babe 🥰, my VIP page is full of spicy posts where you can see my pussy and boobs for free. It’s just $5/month to subscribe, and I post every day 🥰. When you subscribe, you'll get a welcome message with a sexy video of my boobs. Subscribe now and I’ll send you an additional exclusive video 😈. Plus, enjoy more discounts and longer sexting sessionss 💕. @amberjadevip69 @amberjadevip69 @amberjadevip69 @amberjadevip69. Support me, and you won’t regret it 🍆💦💦. I promise you’ll be very pleased and satisfied 🥰😏. @amberjadevip69 @amberjadevip69 @amberjadevip69 @amberjadevip69",
		"Hey, sweetheart🥰 on my VIP page are lots of spicy posts where you can see my pussy and my boobs for free, the subscription it's only 5$/month and I post there everyday🥰 + When you sub you'll get an welcome message with a very nice video, with my boobs, so what about if you subscribe now, I will give you one more video 😈 Maybe some more discounts and longer sexting sesssions💕 @amberjadevip69 @amberjadevip69 @amberjadevip69 @amberjadevip69 Come and support me and you won't regret🍆💦💦 I promise you'll be pleased and satisfied🥰😏 @amberjadevip69 @amberjadevip69 @amberjadevip69 @amberjadevip69"
    ],
	vrajeli: [
	
	    "Honey, just because I'm an onlyfans doesn't mean I'm a cheap whore. I'm a woman with honor, I haven't had too many men in my life (3 to be exact), I'm from a simple, modest family, I'm single, I have no brothers or sisters, and the reason why I do onlyfans is because I prefer to stay at home on my couch, take 2-3 pictures and 2-3 videos and sell them here, it's much better than going to the club and fuck all the freaks. I hope that you appreciate that and I hope that something will develop between the two of us in the future, because so far you are the only man who has opened up to me and told me so much. In general most people come here just with the thought of seeing me naked, but no one ever asks me how am I feeling, how am I doing, have I eaten today, do I need anything, am I sick, am I well, they all think I'm a cheap whore and I hate it. Thank you for coming into my life, sunshine.",
	    "Let's have a pillowtalk now, love just 5 minutes ❤️ I really liked playing with you and you seem like such an interesting person. I've always thought that the kinkiest people are also the smartest, most creative and most intelligent because I believe the thirst for knowledge and curiosity always translates into all fields of life including sex life. Someone limited in thinking just fucks to reproduce but someone smart is always curious to try new things. So if you'd like that as well, I'd love if we could talk for a bit too and know each other better. I'm not here just to fuck myself on camera and I promise I'm not just an online doll that can't string two words together, and to be honest most of the things I talked with you about I've never did them in my real life - I'm not some slutty woman jumping from one dick to another. I am a very sexual person and quite a nymphomaniac when I'm in a relationship hahaha but I don't like the idea of being with multiple men. I mean when I'll be married I want to be able to look my husband in his eyes and vow to him that he's not marrying some whore... Here on OnlyFans I found a safe space for me to explore my fantasies, get to know new and interesting people and of course to make an extra income as well because otherwise with everything that's going on in my life and how corrupt and disgusting our government is here in Romania, it would be literally impossible for me to live a good life and be able to support myself..."
    ],
	dickrate: [
	
	    "Well first of all, your cock it's perfect!!! I love the shape, and the tip of your cock, I'm wondering how would feel inside me I love veiny cocks so there is a +1 point for that, the above part of the tip of your cock, fuck, you'd have to fuck me in all positions to feel it inside me so good🥵🥵The walls inside my pussy and the grips will be destroyed so you'll make me cum in seconds if you want and if the mood it's there for sure😈 So 9/10 💕💕💕💕"
    ],
};

// Generate message in sequence and replace the previous one
function generateMessage(category) {
    const categoryMessages = messages[category];
    const messageContainer = document.getElementById(`${category}Messages`);

    // Check if we reached the end of messages last time
    if (reachedEnd[category]) {
        // Display "End of Messages" and reset for next round
        messageContainer.innerHTML = ''; // Clear the container
        const endMessageElement = document.createElement('p');
        endMessageElement.textContent = "End of Messages"; 
        endMessageElement.style.color = '#b50e29';  // Optional: color for the end message
        messageContainer.appendChild(endMessageElement);

        // Reset the reachedEnd flag and index for the next cycle
        reachedEnd[category] = false;
        currentIndexes[category] = 0; // Reset to start

        return; // Stop here so the "End of Messages" is displayed before starting over
    }

    // Get the current index for the category
    let index = currentIndexes[category];

    // Clear the message container before adding the new message
    messageContainer.innerHTML = ''; // Clear the container

    // Get the message at the current index
    const message = categoryMessages[index];
    
    // Create the new message and add it to the container
    const messageElement = document.createElement('p');
    messageElement.textContent = message;
    messageContainer.appendChild(messageElement);
    
    // Increment the index for the next message
    currentIndexes[category]++;

    // Check if the current message is the last one
    if (currentIndexes[category] === categoryMessages.length) {
        reachedEnd[category] = true; // Mark that we've reached the end
    }
}

// Function to copy message without showing a notification
function copyMessage(category) {
    const messageContainer = document.getElementById(`${category}Messages`);
    const messages = messageContainer.getElementsByTagName('p');
    if (messages.length > 0) {
        const lastMessage = messages[0].textContent; // There's only one message, so just get the first one
        navigator.clipboard.writeText(lastMessage); // Copy to clipboard silently
    }
}
